### ISSUE TITLE
question about the source code

### ISSUE THREAD

**Issue by wmx0708** [CactiLab/code-xNIDS#1]
Excuese me，I'm wondering when can I refer to the source code of the paper 《xNIDS: Explaining Deep Learning-based Network Intrusion Detection Systems for Active Intrusion Responses》

**Comment by akafengfeng** [comment]
Thank you for your interest in our USENIX Security 2023 paper. I wanted to let you know that once we complete the artifacts evaluation process, I will upload the final version of the artifacts. Please refer to the attached [link](https://www.usenix.org/conference/usenixsecurity23/call-for-artifacts ) for information on the process and important dates.

**Comment by wmx0708** [comment]
Excuse me，I've noticed that the fall deadline of the artifacts evaluation process is finished on April 25th,I wonder if I can refer to the artifacts recently.It maybe very helpful for my recent research.
