### ISSUE TITLE
question for the source code

### ISSUE THREAD

**Issue by yixinkai123** [CactiLab/code-xNIDS#10]
def search_proper_input(self):
      step = 0  # Current step
      for i in range(len(self.history_samples)):
          if step <= self.step:
              self.new_input = self.history_samples[-(i+1):]
              print(len(self.new_input))
              model = keras.models.load_model(self.model_path)  # Load the Keras model
              new_current_score  = model.predict(self.new_input,batch_size=1)
              current_score  = new_current_score [-1]
              print("searched current score", current_score)
              current_delta  = abs(current_score - self.original_score)

              if current_delta <= self.delta:
                return self.new_input  # Found proper input
              step += 1
              i *= 2  # Double the value of i
          else:
            print("Cannot find the proper input within the max steps")
            return self.current_sample  # Cannot find proper input

      return None  # Proper input not found within max_steps
Sorry to bother you, when I debug this source code, I found new_current_score  that is  a list,  current_delta  is constant. They can't compare sizes.

**Comment by yixinkai123** [comment]
current_score  = new_current_score [-1]
current_score  = np.mean(np.square(self.new_input - new_current_score)
print("searched current score", current_score)
current_delta  = abs(current_score - self.original_score)

**Comment by yixinkai123** [comment]
current_score = new_current_score [-1]
current_score = np.mean(np.square(self.new_input - new_current_score)   # add  codes
print("searched current score", current_score)
current_delta = abs(current_score - self.original_score)

**Comment by akafengfeng** [comment]
Hi Xinkai, thanks for your interest in our project.  Regarding the current_score,  please check the last example in the demo where the scores are different.
