### ISSUE TITLE
question for source code

### ISSUE THREAD

**Issue by wmx0708** [CactiLab/code-xNIDS#2]
Excuse me，I've noticed that the fall deadline of the artifacts evaluation process is finished on April 25th,I wonder if I can refer to the artifacts recently.It maybe very helpful for my recent research.Looking forward to your reply!

**Comment by akafengfeng** [comment]
Thank you for your interest in our  paper. 
 Please refer to the attached link for information on the process and important dates.
https://www.usenix.org/conference/usenixsecurity23/call-for-artifacts
Here are the relevant dates:
Artifact submission deadline: Wednesday, June 20, 2023
Answering AE reviewer questions: Monday, June 26 to Friday, July 21, 2023
Artifact decisions announced: Tuesday, August 1, 2023
