### ISSUE TITLE
Is this a mistake in your paper? I'm reading it now.

### ISSUE THREAD

**Issue by Trae1ounG** [CactiLab/code-xNIDS#6]
In 6.1.6,"We observe that DL-NIDS achieves a higher ranking than LIME, SHAP, and LEMNA in all the criteria",the DL-NIDS is supposed to be xNIDS right? 😃

**Comment by akafengfeng** [comment]
> In 6.1.6,"We observe that DL-NIDS achieves a higher ranking than LIME, SHAP, and LEMNA in all the criteria",the DL-NIDS is supposed to be xNIDS right? 😃

Hi Trae1ounG, thanks for the feedback. Yeah, you are right, it's a typo here , I am going to check if I can correct it or not.
