### ISSUE TITLE
question for the source code

### ISSUE THREAD

**Issue by Trae1ounG** [CactiLab/code-xNIDS#7]
Sorry to bother you again,I want to know some detail about the code which implements the way to find proper history input.In the 'search_proper_input' function,I think it doesn't fit the paper. In '3.2 Approximating History Inputs',it says in step 1 if  ||f(xt,Xt,l) − f(xt,Xt,k)||1 ≥ δ, then double l ,else l = ⌊l/2⌋. And there is also a limit to the renew times 'U'.But in the source code,I think they do not fit each other.Accually comparing to  In paper l = ⌊l/2⌋ ,I like the code.
```
#original code
def search_proper_input(self):
      step = 0  # Current step
      while step < self.step:
          for i in range(len(self.history_samples)):
              self.new_input = self.history_samples[-(i+1):]
              print(len(self.new_input))
              model = keras.models.load_model(self.model_path)  # Load the Keras model
              new_current_score  = model.predict(self.new_input,batch_size=1)
              current_score  = new_current_score [-1]
              print("searcheed current score", current_score)
              current_delta  = abs(current_score - self.original_score)
              if current_delta <= self.delta:
                return self.new_input  # Found proper input
          self.step += 1
          i *= 2  # Double the value of i
      return None  # Proper input not found within max_steps
```
Question 1 is the step is not renewed,but the self.step,it is meanlingless. Question 2 is it doesn't implement the l = ⌊l/2⌋ and the way to renew l = l * 2 is also wrong I think.
I suppose it may look like this:
```
def search_proper_input_new(self):
      step = 0  # Current step
      for i in range(len(self.history_samples)):
        while step < self.step:
          self.new_input = self.history_samples[-(i+1):]
          print(len(self.new_input))
          model = keras.models.load_model(self.model_path)  # Load the Keras model
          new_current_score  = model.predict(self.new_input,batch_size=1)
          current_score  = new_current_score [-1]
          print("searcheed current score", current_score)
          current_delta  = abs(current_score - self.original_score)
          if current_delta <= self.delta:
            return self.new_input  # Found proper input
          step += 1
          i *= 2  # Double the value of i
        return None
      return None  # Proper input not found within max_steps
```
Thanks for your paper and code,I'm a fresh man in this area,and your reply give me some power to go on.(My English is bad hh) 🤥

**Comment by akafengfeng** [comment]
Hi Trae1ounG, I think you are asking three questions:  1) **self.step**, this parameter is not *used* in the *demo* code but it is definitely meaningful, since it is designed for the optimization of the searching, 2) *  # Double the value of i **, I *intentionally* put it out of the loop in the *demo* code to make the the search operation increase by 1, and 3)  l = ⌊l/2⌋, this function is not implemented in the demo code, since the testcases are relatively simple.  Thanks again for your feedback!

More importantly! If you want to contribute to the code and fix those *bugs*, please create a **pull** request and  your contribution is very welcomed!

**Comment by Trae1ounG** [comment]
> 

But I still think the variable 'i' has something wrong, out of the loop makes it can not be initialized if execute here 
```
i *= 2  # Double the value of i
```
 Yeah, I am not doubling it in the *demo*, I want to see it increase by 1. Since I want to see more searching steps ;).

**Comment by Trae1ounG** [comment]
> 

Thanks for your reply!!Accually I do not understand the whole process wholely,but I will study then know it! 😄 

Ok, Thanks Again!!

**Comment by akafengfeng** [comment]
Your comments regarding the code are correct!!!  The tricky thing here is if I execute the double operation here as designed, the searching steps will be reduced to 2 or 3. 

But when I write the *demo* code, I was thinking about **showing more search steps** which **looks good** but cost more resources. So I put the operation out of the loop. 

I will update the code to clarify this issue!

**Comment by akafengfeng** [comment]
Hi Trae1ounG, I have updated the *demo*  code. Please check it!

**Comment by Trae1ounG** [comment]
> 

I have already seen it!!Thanks for you to apply it,I am so glad to make this contribute!!

**Comment by Trae1ounG** [comment]
> Hi Trae1ounG, I have updated the _demo_ code. Please check it!

Accually I'm a student from UESTC hh,I have to do a paper report so I read this one,and it's my namely first time to do this.It is kind of difficult but I'm very glad and surprise to hava a communication with you!! I hope I can do as good as you in the future!

**Comment by akafengfeng** [comment]
Thank you  for reaching out to me! I'm thrilled to hear that you found my work helpful for your own research. Wishing you all the best in your studies and future achievements!

**Comment by Trae1ounG** [comment]
> Thank you for reaching out to me! I'm thrilled to hear that you found my work helpful for your own research. Wishing you all the best in your studies and future achievements!

Hi,I'm here to say thanks again! With your help i'm in the Smart Internet Group in SIGS!And it's may have the similar research topic like you,so I also want to ask if I can have communication methods  with you such as wechat,I'm very curious about this topic!Thanks a lot!

**Comment by akafengfeng** [comment]
> > Thank you for reaching out to me! I'm thrilled to hear that you found my work helpful for your own research. Wishing you all the best in your studies and future achievements!
> 
> Hi,I'm here to say thanks again! With your help i'm in the Smart Internet Group in SIGS!And it's may have the similar research topic like you,so I also want to ask if I can have communication methods with you such as wechat,I'm very curious about this topic!Thanks a lot!

Congratulations on your acceptance to the Smart Internet Group in SIGS! If you would like to discuss those research topics, please take a moment to send me an email at fengwei@buffalo.edu.  *We can also discuss through wechat, but please send me an eamil first.*

**Comment by Trae1ounG** [comment]
> > > Thank you for reaching out to me! I'm thrilled to hear that you found my work helpful for your own research. Wishing you all the best in your studies and future achievements!
> > 
> > 
> > Hi,I'm here to say thanks again! With your help i'm in the Smart Internet Group in SIGS!And it's may have the similar research topic like you,so I also want to ask if I can have communication methods with you such as wechat,I'm very curious about this topic!Thanks a lot!
> 
> Congratulations on your acceptance to the Smart Internet Group in SIGS! If you would like to discuss those research topics, please take a moment to send me an email at [fengwei@buffalo.edu](mailto:fengwei@buffalo.edu).

Ok I know that,now I don't know many useful things,I'll have a communication with you in the future!
